from __future__ import annotations

from typing import Protocol, runtime_checkable

from soundboard.core.models import Sound


class PlayHandle(Protocol):
    def is_playing(self) -> bool: ...
    def stop(self) -> None: ...
    def wait(self) -> None: ...


@runtime_checkable
class Player(Protocol):
    def play(self, sound: Sound) -> PlayHandle: ...
    def stop_all(self) -> None: ...
    def close(self) -> None: ...
